#!/bin/sh

mkdir -p /etc/dovecot/private
ln -s /etc/ssl/certs/moja-poczta.net.pem /etc/dovecot/dovecot.pem
ln -s /etc/ssl/private/moja-poczta.net.pem /etc/dovecot/private/dovecot.pem

echo "DOVECOT: serwer"
apt-get install -qq -y --force-yes dovecot-core dovecot-imapd dovecot-lmtpd

echo "DOVECOT: backendy"
apt-get install -qq -y --force-yes dovecot-mysql dovecot-pgsql